[window]
padding = { x = 14, y = 12 }
dynamic_padding = true

[colors.primary]
background = '#1e222a'
foreground = '#abb2bf'

[colors.selection]
text = '#1e222a'
background = '#3e4451'

[colors.cursor]
text = '#1e222a'
cursor = '#abb2bf'

[colors.normal]
black   = '#1e222a'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
